//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectoSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atributes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atributes()
        {
            this.Student_Atribute = new HashSet<Student_Atributes>();
        }
    
        public int Id { get; set; }
        public string AtributeName { get; set; }
        public string AtributeAbbr { get; set; }
        public int ProjectsId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Atributes> Student_Atribute { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
